QUESTION_MODE = "mode"
QUESTION_GZIP = "gzip"
QUESTION_MULTIPLE_LIGHTS = "multiple_lights"
QUESTION_NUM_LIGHTS = "num_lights"
QUESTION_EXPORT_FILENAME = "export_filename"
QUESTION_DURATION = "duration"
QUESTION_CHARGING_DEVICE_TYPE = "charging_device_type"
