powerprofile:
  - changed-files:
    - any-glob-to-any-file: profile_library/**

documentation:
  - changed-files:
    - any-glob-to-any-file: docs/**

enhancement:
 - head-branch: ['^feat', 'feature']

bug:
  - head-branch: ['^fix', 'fix']

measure-tool:
  - changed-files:
      - any-glob-to-any-file:
          - utils/measure/**
          - .github/actions/build-measure-docker/**
          - .github/release-drafter-measure.yml
          - .github/workflows/prepare-measure-release.yml
          - .github/workflows/publish-measure-image.yml
          - .github/workflows/test-measure.yml
