name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: 'v'
change-template: '- #$NUMBER $TITLE @$AUTHOR'
sort-direction: ascending
exclude-contributors:
  - 'github-actions[bot]'
  - 'github-actions'
  - 'renovate[bot]'
  - 'renovate'
  - 'pre-commit-ci'
  - 'pre-commit-ci[bot]'
  - 'bramstroker'
  - 'crowdin-bot'
exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
  - 'measure-tool'
categories:
  - title: '💡 Power profiles'
    labels:
      - 'powerprofile'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  <!-- SUPPORTERS_SECTION -->
