from typing import Protocol

from measure.controller.answerable_protocol import Answerable


class MediaController(Answerable, Protocol):
    def set_volume(self, volume: int) -> None: ...

    def mute_volume(self) -> None: ...

    def play_audio(self, stream_url: str) -> None: ...

    def turn_off(self) -> None: ...
