import json
from pathlib import Path

from measure.cli.profile import _ask_mains_voltage, _metadata_defaults, _prompt_device_specs, prepare_profile
from measure.contribution.prepare import ProfilePreparationError
from measure.profile.specifications import DeviceSpecField
import pytest


def write_artifacts(path: Path) -> dict[str, object]:
    path.mkdir(parents=True)
    model: dict[str, object] = {
        "name": "Original product name",
        "measure_device": "Original meter",
        "measure_description": "Generated by the measurement runner",
        "calculation_strategy": "linear",
    }
    (path / "model.json").write_text(json.dumps(model), encoding="utf-8")
    return model


def write_library(path: Path) -> None:
    path.mkdir()
    (path / "model_schema.json").write_text("{}", encoding="utf-8")


@pytest.mark.parametrize("directory", ["measurement", f"session-{'a' * 32}"])
def test_internal_artifact_directory_is_not_a_default_model_id(directory: str) -> None:
    assert _metadata_defaults(Path(directory), {})["model_id"] == ""


def test_missing_product_name_is_rejected_during_preparation(tmp_path: Path) -> None:
    artifacts = tmp_path / "export" / "MODEL-1"
    write_artifacts(artifacts)
    (artifacts / "model.json").write_text('{"calculation_strategy":"linear"}', encoding="utf-8")
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "metadata.json"
    metadata_path.write_text(
        json.dumps(
            {
                "manufacturer": "Acme",
                "author": {"name": "Test User", "github": "test-user"},
                "mains_voltage": 230,
            }
        ),
        encoding="utf-8",
    )
    with pytest.raises(ProfilePreparationError, match="Enter the product name") as error:
        prepare_profile(
            [
                "prepare",
                str(artifacts),
                "--metadata",
                str(metadata_path),
                "--non-interactive",
                "--library-root",
                str(library),
            ]
        )
    assert error.value.field == "product_name"


def test_non_interactive_cli_prepares_enriched_package_without_changing_artifacts(tmp_path: Path) -> None:
    artifacts = tmp_path / "export" / "MODEL-1"
    original_model = write_artifacts(artifacts)
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "profile-metadata.json"
    metadata_path.write_text(
        json.dumps(
            {
                "manufacturer": "Acme",
                "product_name": "Desk Lamp",
                "aliases": ["Lamp v2", "Lamp v2"],
                "gtins": ["12345678", "1234567890123"],
                "product_url": "https://example.com/desk-lamp",
                "mains_voltage": 230,
                "device_specs": {"rated_power": 8.5},
                "measure_device": "Shelly PM Mini Gen3",
                "measure_device_firmware": "1.7.0",
                "measure_description": "Measured at 230 V",
                "author": {"name": "Test User", "github": "test-user"},
            },
        ),
        encoding="utf-8",
    )

    result = prepare_profile(
        [
            "prepare",
            str(artifacts),
            "--metadata",
            str(metadata_path),
            "--non-interactive",
            "--library-root",
            str(library),
        ],
    )

    prepared_model_path = result.output_directory / "profile_library" / "acme" / "MODEL-1" / "model.json"
    prepared_model = json.loads(prepared_model_path.read_text(encoding="utf-8"))
    assert prepared_model == {
        "aliases": ["Lamp v2"],
        "authors": [{"github": "test-user", "name": "Test User"}],
        "calculation_strategy": "linear",
        "device_specs": {"rated_power": 8.5},
        "ean": ["12345678", "1234567890123"],
        "measure_description": "Measured at 230 V",
        "measure_device": "Shelly PM Mini Gen3",
        "measure_device_firmware": "1.7.0",
        "mains_voltage": 230,
        "name": "Desk Lamp",
        "product_url": "https://example.com/desk-lamp",
    }
    assert json.loads((artifacts / "model.json").read_text(encoding="utf-8")) == original_model
    assert (result.output_directory / "profile_library" / "acme" / "manufacturer.json").is_file()


@pytest.mark.parametrize(
    "metadata, message",
    [
        ({"manufacturer": "Acme"}, "Contributor name and GitHub username are required"),
        (
            {
                "manufacturer": "Acme",
                "author": {"name": "Test User", "github": "test-user"},
                "gtins": ["not-a-barcode"],
            },
            "invalid GTIN",
        ),
        (
            {
                "manufacturer": "Acme",
                "manufacturer_directory": "custom-directory",
                "author": {"name": "Test User", "github": "test-user"},
            },
            "Unsupported metadata field: manufacturer_directory",
        ),
    ],
)
def test_non_interactive_cli_reports_incomplete_or_invalid_metadata(
    tmp_path: Path,
    metadata: dict[str, object],
    message: str,
) -> None:
    artifacts = tmp_path / "MODEL-1"
    write_artifacts(artifacts)
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "metadata.json"
    metadata_path.write_text(json.dumps(metadata), encoding="utf-8")

    with pytest.raises(ProfilePreparationError, match=message):
        prepare_profile(
            [
                "prepare",
                str(artifacts),
                "--metadata",
                str(metadata_path),
                "--non-interactive",
                "--library-root",
                str(library),
            ],
        )


def test_cli_prompts_for_schema_backed_device_specifications_individually() -> None:
    answers = iter(["9.5", "zigbee, wifi", "GU10"])
    questions: list[str] = []

    def prompt(question: str) -> str:
        questions.append(question)
        return next(answers)

    result = _prompt_device_specs(
        prompt,
        (
            DeviceSpecField("rated_power", "Rated power", "", "number"),
            DeviceSpecField(
                "connectivity",
                "Connectivity",
                "",
                "string",
                collection="array",
                options=("zigbee", "wifi"),
            ),
            DeviceSpecField(
                "socket",
                "Socket",
                "",
                "string",
                collection="scalar_or_array",
                options=("E27", "GU10"),
            ),
        ),
        None,
    )

    assert result == {"rated_power": 9.5, "connectivity": ["zigbee", "wifi"], "socket": "GU10"}
    assert all("JSON" not in question for question in questions)


def test_cli_mains_voltage_only_accepts_supported_values(capsys: pytest.CaptureFixture[str]) -> None:
    answers = iter(["110", "230"])

    assert _ask_mains_voltage(lambda _question: next(answers), None) == 230
    assert "must be one of 120, 230" in capsys.readouterr().out


@pytest.mark.parametrize("voltage", [110, 240, "230", None])
def test_non_interactive_cli_rejects_unsupported_voltage_in_existing_model(tmp_path: Path, voltage: object) -> None:
    artifacts = tmp_path / "MODEL-1"
    model = write_artifacts(artifacts)
    model.update({"mains_voltage": voltage, "authors": [{"name": "Test User", "github": "tester"}]})
    (artifacts / "model.json").write_text(json.dumps(model), encoding="utf-8")
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "metadata.json"
    metadata_path.write_text(json.dumps({"manufacturer": "Acme"}), encoding="utf-8")

    with pytest.raises(ProfilePreparationError, match="Nominal mains voltage must be either 120 or 230") as error:
        prepare_profile(
            [
                "prepare",
                str(artifacts),
                "--metadata",
                str(metadata_path),
                "--non-interactive",
                "--library-root",
                str(library),
            ],
        )

    assert error.value.field == "mains_voltage"
    assert json.loads((artifacts / "model.json").read_text(encoding="utf-8")) == model


@pytest.mark.parametrize("use_range", [False, True])
def test_cli_can_replace_unsupported_existing_voltage(tmp_path: Path, use_range: bool) -> None:
    artifacts = tmp_path / "MODEL-1"
    model = write_artifacts(artifacts)
    model.update({"mains_voltage": 240, "authors": [{"name": "Test User", "github": "tester"}]})
    if use_range:
        model["voltage_range"] = {"min": 225, "max": 235}
    (artifacts / "model.json").write_text(json.dumps(model), encoding="utf-8")
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "metadata.json"
    values: dict[str, object] = {"manufacturer": "Acme"}
    if not use_range:
        values["mains_voltage"] = 230
    metadata_path.write_text(json.dumps(values), encoding="utf-8")

    result = prepare_profile(
        [
            "prepare",
            str(artifacts),
            "--non-interactive",
            "--library-root",
            str(library),
            "--metadata",
            str(metadata_path),
        ]
    )

    prepared = result.output_directory / "profile_library" / "acme" / "MODEL-1" / "model.json"
    assert json.loads(prepared.read_text(encoding="utf-8"))["mains_voltage"] == 230
