import json
from pathlib import Path
import sys

from measure.cli.profile import _ask_mains_voltage, _metadata_defaults, _prompt_device_specs, main, prepare_profile
from measure.profile.prepare import ProfilePreparationError
from measure.profile.specifications import DeviceSpecField
import pytest


def write_artifacts(path: Path) -> dict[str, object]:
    path.mkdir(parents=True)
    model: dict[str, object] = {
        "name": "Original product name",
        "measure_device": "Original meter",
        "measure_description": "Generated by the measurement runner",
        "calculation_strategy": "linear",
    }
    (path / "model.json").write_text(json.dumps(model), encoding="utf-8")
    return model


def write_library(path: Path) -> None:
    path.mkdir()
    (path / "model_schema.json").write_text("{}", encoding="utf-8")


@pytest.mark.parametrize("use_voltage_range", [False, True])
def test_interactive_preparation_preserves_defaults_and_unknown_specifications(
    tmp_path: Path,
    use_voltage_range: bool,
) -> None:
    artifacts = tmp_path / "MODEL-1"
    model = write_artifacts(artifacts)
    model.update(
        {
            "device_type": "light",
            "standby_power": 0.3,
            "mains_voltage": 230,
            "aliases": ["Lamp v2"],
            "gtin": ["12345678"],
            "product_url": "https://example.com/lamp",
            "device_specs": {"rated_power": 9.5, "legacy_field": "keep"},
            "authors": [{"name": "Test User", "github": "tester", "email": "test@example.com"}],
        }
    )
    if use_voltage_range:
        model["voltage_range"] = {"min": 225, "max": 235}
    (artifacts / "model.json").write_text(json.dumps(model), encoding="utf-8")
    library = tmp_path / "profile_library"
    write_library(library)
    schema = {
        "properties": {
            "device_type": {"enum": ["light"]},
            "device_specs": {"properties": {"rated_power": {"type": "number"}}},
        },
    }
    (library / "model_schema.json").write_text(json.dumps(schema), encoding="utf-8")
    metadata = tmp_path / "metadata.json"
    metadata.write_text('{"manufacturer":"Acme"}', encoding="utf-8")
    questions: list[str] = []

    def accept_default(question: str) -> str:
        questions.append(question)
        return ""

    result = prepare_profile(
        ["prepare", str(artifacts), "--metadata", str(metadata), "--library-root", str(library)],
        prompt=accept_default,
    )

    prepared = result.output_directory / "profile_library" / "acme" / "MODEL-1" / "model.json"
    assert json.loads(prepared.read_text(encoding="utf-8")) == model
    assert json.loads((artifacts / "model.json").read_text(encoding="utf-8")) == model
    assert any("Rated power [9.5]" in question for question in questions)
    assert any("Nominal mains voltage" in question for question in questions) is not use_voltage_range


def test_interactive_preparation_reprompts_required_fields_and_accepts_edits(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    artifacts = tmp_path / "MODEL-1"
    write_artifacts(artifacts)
    library = tmp_path / "profile_library"
    write_library(library)
    answers = iter(
        [
            "",
            " Acme ",
            "MODEL-2",
            "Desk lamp",
            "Alias one, Alias two",
            "12345678",
            "",
            "not a number",
            "230",
            "New meter",
            "1.2",
            "Measured indoors",
            "Test User",
            "tester",
            "",
        ]
    )

    result = prepare_profile(
        ["prepare", str(artifacts), "--library-root", str(library)],
        prompt=lambda _: next(answers),
    )

    prepared = result.output_directory / "profile_library" / "acme" / "MODEL-2" / "model.json"
    model = json.loads(prepared.read_text(encoding="utf-8"))
    assert model["name"] == "Desk lamp"
    assert model["aliases"] == ["Alias one", "Alias two"]
    assert model["gtin"] == ["12345678"]
    assert model["mains_voltage"] == 230
    assert model["measure_device"] == "New meter"
    assert model["measure_device_firmware"] == "1.2"
    assert model["measure_description"] == "Measured indoors"
    assert model["authors"] == [{"name": "Test User", "github": "tester"}]
    assert "product_url" not in model
    output = capsys.readouterr().out
    assert "Manufacturer is required" in output
    assert "Nominal mains voltage must be one of" in output
    assert next(answers, None) is None


@pytest.mark.parametrize(
    "field,answers,default,expected,feedback",
    [
        (DeviceSpecField("value", "Value", "", "boolean"), ["maybe", "YES"], None, True, "must be yes or no"),
        (DeviceSpecField("value", "Value", "", "boolean"), ["no"], None, False, ""),
        (DeviceSpecField("value", "Value", "", "boolean"), [""], True, True, ""),
        (DeviceSpecField("value", "Value", "", "boolean"), [""], False, False, ""),
        (DeviceSpecField("value", "Value", "", "boolean"), [""], None, None, ""),
        (DeviceSpecField("value", "Value", "", "number"), ["bad", "9.5"], None, 9.5, "must be a number"),
        (DeviceSpecField("value", "Value", "", "integer"), ["1.5", "2"], None, 2, "must be a whole number"),
        (DeviceSpecField("value", "Value", "", "integer"), [""], None, None, ""),
        (
            DeviceSpecField("value", "Value", "", "integer", collection="array"),
            ["1,x", "1,2"],
            None,
            [1, 2],
            "list of numbers",
        ),
        (DeviceSpecField("value", "Value", "", "number", collection="array"), ["1.5,2.5"], None, [1.5, 2.5], ""),
        (DeviceSpecField("value", "Value", "", "number", collection="array"), [""], None, None, ""),
        (DeviceSpecField("value", "Value", "", "number", collection="scalar_or_array"), [""], 9.5, 9.5, ""),
        (
            DeviceSpecField("value", "Value", "", "string", options=("E27", "GU10")),
            ["invalid", "GU10"],
            None,
            "GU10",
            "not an allowed value",
        ),
        (
            DeviceSpecField("value", "Value", "", "string", collection="array", options=("wifi", "zigbee")),
            ["wifi,bluetooth", "wifi,zigbee"],
            None,
            ["wifi", "zigbee"],
            "not an allowed value",
        ),
    ],
)
def test_device_specification_prompts_validate_values_and_preserve_types(
    field: DeviceSpecField,
    answers: list[str],
    default: object,
    expected: object,
    feedback: str,
    capsys: pytest.CaptureFixture[str],
) -> None:
    responses = iter(answers)

    result = _prompt_device_specs(lambda _: next(responses), [field], {"value": default, "legacy": "keep"})

    assert result == ({"value": expected, "legacy": "keep"} if expected is not None else {"legacy": "keep"})
    if expected is not None:
        assert type(result["value"]) is type(expected)
    assert feedback in capsys.readouterr().out
    assert next(responses, None) is None


@pytest.mark.parametrize(
    "contents,message", [(None, "File does not exist"), ("{", "Invalid JSON"), ("[]", "must contain a JSON object")]
)
def test_cli_reports_unreadable_model_without_creating_output(
    tmp_path: Path,
    contents: str | None,
    message: str,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    artifacts = tmp_path / "MODEL-1"
    artifacts.mkdir()
    if contents is not None:
        (artifacts / "model.json").write_text(contents, encoding="utf-8")
    monkeypatch.setattr(sys, "argv", ["powercalc-profile", "prepare", str(artifacts), "--non-interactive"])

    with pytest.raises(SystemExit) as raised:
        main()

    assert raised.value.code == 2
    assert message in capsys.readouterr().err
    assert not (artifacts / "prepared").exists()


@pytest.mark.parametrize("library_exists", [False, True])
def test_cli_reports_missing_library_or_schema(tmp_path: Path, library_exists: bool) -> None:
    artifacts = tmp_path / "MODEL-1"
    write_artifacts(artifacts)
    library = tmp_path / "profile_library"
    if library_exists:
        library.mkdir()
    message = "Model schema does not exist" if library_exists else "Profile library checkout was not found"

    with pytest.raises(ProfilePreparationError, match=message):
        prepare_profile(["prepare", str(artifacts), "--non-interactive", "--library-root", str(library)])


def test_cli_main_reports_prepared_files_and_duplicate_warning(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    artifacts = tmp_path / "MODEL-1"
    model = write_artifacts(artifacts)
    model.update({"mains_voltage": 230, "authors": [{"name": "Test User", "github": "tester"}]})
    (artifacts / "model.json").write_text(json.dumps(model), encoding="utf-8")
    library = tmp_path / "profile_library"
    write_library(library)
    existing = library / "other" / "lamp"
    existing.mkdir(parents=True)
    (existing / "model.json").write_text(json.dumps(model), encoding="utf-8")
    metadata = tmp_path / "metadata.json"
    metadata.write_text('{"manufacturer":"Acme"}', encoding="utf-8")
    output = tmp_path / "prepared"
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "powercalc-profile",
            "prepare",
            str(artifacts),
            "--non-interactive",
            "--metadata",
            str(metadata),
            "--library-root",
            str(tmp_path),
            "--output",
            str(output),
            "--schema",
            str(library / "model_schema.json"),
        ],
    )

    main()

    captured = capsys.readouterr()
    assert f"Prepared profile written to {output}" in captured.out
    assert "profile_library/acme/MODEL-1/model.json" in captured.out
    assert "Warning: Possible duplicate profile: profile_library/other/lamp/model.json" in captured.err
    assert (output / "profile_library" / "acme" / "MODEL-1" / "model.json").is_file()


@pytest.mark.parametrize("directory", ["measurement", f"session-{'a' * 32}"])
def test_internal_artifact_directory_is_not_a_default_model_id(directory: str) -> None:
    assert _metadata_defaults(Path(directory), {})["model_id"] == ""


def test_missing_product_name_is_rejected_during_preparation(tmp_path: Path) -> None:
    artifacts = tmp_path / "export" / "MODEL-1"
    write_artifacts(artifacts)
    (artifacts / "model.json").write_text('{"calculation_strategy":"linear"}', encoding="utf-8")
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "metadata.json"
    metadata_path.write_text(
        json.dumps(
            {
                "manufacturer": "Acme",
                "author": {"name": "Test User", "github": "test-user"},
                "mains_voltage": 230,
            }
        ),
        encoding="utf-8",
    )
    with pytest.raises(ProfilePreparationError, match="Enter the product name") as error:
        prepare_profile(
            [
                "prepare",
                str(artifacts),
                "--metadata",
                str(metadata_path),
                "--non-interactive",
                "--library-root",
                str(library),
            ]
        )
    assert error.value.field == "product_name"


def test_non_interactive_cli_prepares_enriched_package_without_changing_artifacts(tmp_path: Path) -> None:
    artifacts = tmp_path / "export" / "MODEL-1"
    original_model = write_artifacts(artifacts)
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "profile-metadata.json"
    metadata_path.write_text(
        json.dumps(
            {
                "manufacturer": "Acme",
                "product_name": "Desk Lamp",
                "aliases": ["Lamp v2", "Lamp v2"],
                "gtins": ["12345678", "1234567890123"],
                "product_url": "https://example.com/desk-lamp",
                "mains_voltage": 230,
                "device_specs": {"rated_power": 8.5},
                "measure_device": "Shelly PM Mini Gen3",
                "measure_device_firmware": "1.7.0",
                "measure_description": "Measured at 230 V",
                "author": {"name": "Test User", "github": "test-user"},
            },
        ),
        encoding="utf-8",
    )

    result = prepare_profile(
        [
            "prepare",
            str(artifacts),
            "--metadata",
            str(metadata_path),
            "--non-interactive",
            "--library-root",
            str(library),
        ],
    )

    prepared_model_path = result.output_directory / "profile_library" / "acme" / "MODEL-1" / "model.json"
    prepared_model = json.loads(prepared_model_path.read_text(encoding="utf-8"))
    assert prepared_model == {
        "aliases": ["Lamp v2"],
        "authors": [{"github": "test-user", "name": "Test User"}],
        "calculation_strategy": "linear",
        "device_specs": {"rated_power": 8.5},
        "gtin": ["12345678", "1234567890123"],
        "measure_description": "Measured at 230 V",
        "measure_device": "Shelly PM Mini Gen3",
        "measure_device_firmware": "1.7.0",
        "mains_voltage": 230,
        "name": "Desk Lamp",
        "product_url": "https://example.com/desk-lamp",
    }
    assert json.loads((artifacts / "model.json").read_text(encoding="utf-8")) == original_model
    assert (result.output_directory / "profile_library" / "acme" / "manufacturer.json").is_file()


@pytest.mark.parametrize(
    "metadata, message",
    [
        ({"manufacturer": "Acme"}, "Contributor name and GitHub username are required"),
        (
            {
                "manufacturer": "Acme",
                "author": {"name": "Test User", "github": "test-user"},
                "gtins": ["not-a-barcode"],
            },
            "invalid GTIN",
        ),
        (
            {
                "manufacturer": "Acme",
                "manufacturer_directory": "custom-directory",
                "author": {"name": "Test User", "github": "test-user"},
            },
            "Unsupported metadata field: manufacturer_directory",
        ),
    ],
)
def test_non_interactive_cli_reports_incomplete_or_invalid_metadata(
    tmp_path: Path,
    metadata: dict[str, object],
    message: str,
) -> None:
    artifacts = tmp_path / "MODEL-1"
    write_artifacts(artifacts)
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "metadata.json"
    metadata_path.write_text(json.dumps(metadata), encoding="utf-8")

    with pytest.raises(ProfilePreparationError, match=message):
        prepare_profile(
            [
                "prepare",
                str(artifacts),
                "--metadata",
                str(metadata_path),
                "--non-interactive",
                "--library-root",
                str(library),
            ],
        )


def test_cli_prompts_for_schema_backed_device_specifications_individually() -> None:
    answers = iter(["9.5", "zigbee, wifi", "GU10"])
    questions: list[str] = []

    def prompt(question: str) -> str:
        questions.append(question)
        return next(answers)

    result = _prompt_device_specs(
        prompt,
        (
            DeviceSpecField("rated_power", "Rated power", "", "number"),
            DeviceSpecField(
                "connectivity",
                "Connectivity",
                "",
                "string",
                collection="array",
                options=("zigbee", "wifi"),
            ),
            DeviceSpecField(
                "socket",
                "Socket",
                "",
                "string",
                collection="scalar_or_array",
                options=("E27", "GU10"),
            ),
        ),
        None,
    )

    assert result == {"rated_power": 9.5, "connectivity": ["zigbee", "wifi"], "socket": "GU10"}
    assert all("JSON" not in question for question in questions)


def test_cli_mains_voltage_only_accepts_supported_values(capsys: pytest.CaptureFixture[str]) -> None:
    answers = iter(["110", "230"])

    assert _ask_mains_voltage(lambda _question: next(answers), None) == 230
    assert "must be one of 120, 230" in capsys.readouterr().out


@pytest.mark.parametrize("voltage", [110, 240, "230", None])
def test_non_interactive_cli_rejects_unsupported_voltage_in_existing_model(tmp_path: Path, voltage: object) -> None:
    artifacts = tmp_path / "MODEL-1"
    model = write_artifacts(artifacts)
    model.update({"mains_voltage": voltage, "authors": [{"name": "Test User", "github": "tester"}]})
    (artifacts / "model.json").write_text(json.dumps(model), encoding="utf-8")
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "metadata.json"
    metadata_path.write_text(json.dumps({"manufacturer": "Acme"}), encoding="utf-8")

    with pytest.raises(ProfilePreparationError, match="Nominal mains voltage must be either 120 or 230") as error:
        prepare_profile(
            [
                "prepare",
                str(artifacts),
                "--metadata",
                str(metadata_path),
                "--non-interactive",
                "--library-root",
                str(library),
            ],
        )

    assert error.value.field == "mains_voltage"
    assert json.loads((artifacts / "model.json").read_text(encoding="utf-8")) == model


@pytest.mark.parametrize("use_range", [False, True])
def test_cli_can_replace_unsupported_existing_voltage(tmp_path: Path, use_range: bool) -> None:
    artifacts = tmp_path / "MODEL-1"
    model = write_artifacts(artifacts)
    model.update({"mains_voltage": 240, "authors": [{"name": "Test User", "github": "tester"}]})
    if use_range:
        model["voltage_range"] = {"min": 225, "max": 235}
    (artifacts / "model.json").write_text(json.dumps(model), encoding="utf-8")
    library = tmp_path / "profile_library"
    write_library(library)
    metadata_path = tmp_path / "metadata.json"
    values: dict[str, object] = {"manufacturer": "Acme"}
    if not use_range:
        values["mains_voltage"] = 230
    metadata_path.write_text(json.dumps(values), encoding="utf-8")

    result = prepare_profile(
        [
            "prepare",
            str(artifacts),
            "--non-interactive",
            "--library-root",
            str(library),
            "--metadata",
            str(metadata_path),
        ]
    )

    prepared = result.output_directory / "profile_library" / "acme" / "MODEL-1" / "model.json"
    assert json.loads(prepared.read_text(encoding="utf-8"))["mains_voltage"] == 230
