name: Powercalc Measure
version: "0.2.0"
slug: powercalc_measure
description: Create Powercalc power profiles from Home Assistant entities
url: https://docs.powercalc.nl/contributing/measure/home-assistant-app/
arch:
  - aarch64
  - amd64
image: ghcr.io/bramstroker/powercalc-measure-app
stage: experimental
ingress: true
ingress_stream: true
panel_icon: mdi:lightning-bolt
homeassistant_api: true
environment:
  MEASURE_TRUSTED_INGRESS_ONLY: "true"
backup: cold
options:
  debug_logging: false
schema:
  debug_logging: bool
