name: Crowdin download

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions: write-all

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: crowdin
          create_pull_request: true
          pull_request_title: 'Update translations'
          pull_request_body: 'New Crowdin translations submitted'
          pull_request_base_branch_name: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
