name: Generate plots

on:
  push:
    paths:
      - '**/*.csv.gz'
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    name: Generate plots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          working-directory: './utils/visualize'
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
      - name: Run visualization tool
        run: bash ./utils/visualize/generate-all.sh ./profile_library
      - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        if: github.ref == 'refs/heads/master'
        with:
          message: 'chore: generate plots'
          pull: '--rebase --autostash'
          push: 'origin HEAD:master --force'
