name: Comment with PR plots

on:
  workflow_run:
    workflows: [Generate PR plots]
    types:
      - completed

permissions:
  issues: write
  contents: read
  actions: read

jobs:
  upload:
    name: Upload plots to Imgur
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests[0].number != null
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: plots
          path: artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Checkout comment action
        uses: actions/checkout@v7
      - name: Upload the plots to Imgur
        uses: devicons/public-upload-to-imgur@v2
        id: imgur_step
        with:
          path: ./artifacts/**/*.png
          client_id: ${{secrets.IMGUR_CLIENT_ID}}
      - name: Build PR message
        id: build-pr-message
        run: |
          {
            echo 'PR_MESSAGE<<EOF'
            echo "Thank you for submitting light measurements!"
            echo -e "Here are some visualizations for the CSV files.\n"
          } >> "$GITHUB_OUTPUT"
          for url in ${{ join(fromJSON(steps.imgur_step.outputs.imgur_urls), ' ') }}
          do
            echo "![Image](${url})" >> "$GITHUB_OUTPUT"
          done
          echo 'EOF' >> "$GITHUB_OUTPUT"
      - name: Post Comment on PR
        uses: ./.github/actions/upsert-pr-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: ${{ steps.build-pr-message.outputs.PR_MESSAGE }}
          match-text: Thank you for submitting
