name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_zip_file:
    if: startsWith(github.event.release.tag_name, 'v')
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: "Set manifest version number"
        run: |
          python3 "${{ github.workspace }}/.github/scripts/update_hacs_manifest.py" --version "${GITHUB_REF_NAME}"
      - name: Create zip
        run: |
          cd custom_components/powercalc
          zip powercalc.zip -r ./
      - name: Upload zip to release
        run: gh release upload "${GITHUB_REF_NAME}" ./custom_components/powercalc/powercalc.zip#powercalc.zip --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
