name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
      - 'uv.lock'

permissions:
  contents: read

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
      - name: Install dependencies
        run: uv sync --group dev
      - name: Prepare test env
        run: bash tests/setup.sh
      - name: Run tests
        run: |
          uv run pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            --cov custom_components.powercalc \
            --cov-report xml \
            -o console_output_style=count \
            -p no:sugar \
            tests
          uv run coverage lcov
      - name: Upload Coverage Results
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
