name: Test measure util

on:
  workflow_dispatch:
  push:
    paths:
      - 'utils/measure/**'
  pull_request:
    paths:
      - 'utils/measure/**'

permissions:
  contents: read

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          working-directory: './utils/measure'
          python-version: '3.14'
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
      - name: Run tests
        run: |
          cd ./utils/measure && uv run --extra dev pytest \
            -qq \
            --durations=10 \
            -o console_output_style=count \
            -p no:sugar \
            tests

  docker:
    runs-on: "ubuntu-latest"
    name: Build Docker image
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Build Docker image
        uses: ./.github/actions/build-measure-docker
