name: Validate translations

on:
  pull_request:
    paths:
      - custom_components/powercalc/translations/*.json
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate_translations:
    name: Validate translation files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.14'
      - name: Validate translation files
        run: python ${{ github.workspace }}/.github/scripts/validate_translations.py
