name: Validate translations

on:
  pull_request:
    paths:
      - custom_components/powercalc/translations/*.json
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate_translations:
    name: Validate translation files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.14'
      - name: Validate translation files
        run: python ${{ github.workspace }}/.github/scripts/validate_translations.py
