name: Validate HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  validate-hassfest:
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: validation
        uses: home-assistant/actions/hassfest@e3fb68ebda13d88a0d695082f471ba2c83d025fb # master

  validate-hacs:
    name: HACS validation
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: validation
        uses: "hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa" # main
        with:
          category: "integration"
