"""Text rendered into the profile-library pull request: branch name, commit message, title, and body."""

from __future__ import annotations

from collections.abc import Sequence

from measure.contribution.models import ContributionJob, ContributionPreview


def deterministic_branch_name(preview: ContributionPreview) -> str:
    manufacturer = _branch_part(preview.manufacturer_directory)
    model = _branch_part(preview.model_directory)
    return f"powercalc-profile-{manufacturer}-{model}"


def conventional_commit_message(preview: ContributionPreview) -> str:
    return f"feat(profile): add {preview.manufacturer_directory} {preview.model_directory}"


def pull_request_title(preview: ContributionPreview) -> str:
    return f"Add {preview.manufacturer_directory} {preview.model_directory} power profile"


def pull_request_body(job: ContributionJob) -> str:
    return profile_pull_request_body(
        manufacturer=job.metadata.manufacturer,
        model_id=job.metadata.model_id,
        product_name=job.metadata.product_name or job.preview.model_directory,
        measure_device=job.metadata.measure_device,
        measure_type=job.metadata.measure_type,
        notes=job.metadata.notes,
        file_paths=[file.path for file in job.preview.files],
        warnings=job.preview.warnings,
    )


def profile_pull_request_body(
    *,
    manufacturer: str,
    model_id: str,
    product_name: str,
    measure_device: str | None,
    measure_type: str | None,
    notes: str,
    file_paths: Sequence[str],
    warnings: Sequence[str] = (),
) -> str:
    device_lines = [
        f"- Manufacturer: {manufacturer}",
        f"- Model ID: {model_id}",
        f"- Product name: {product_name}",
    ]
    if measure_device:
        device_lines.append(f"- Measurement device: {measure_device}")
    home_assistant = (
        f"- Measure type: {measure_type}\n"
        if measure_type
        else "Generated by Powercalc Measure from a completed measurement session.\n"
    )
    files = "\n".join(f"- `{path}`" for path in file_paths) or "- None"
    warning_lines = "\n".join(f"- {warning}" for warning in warnings) or "- None"
    additional_info = notes or "Generated and validated by Powercalc Measure."
    return (
        "## Device information\n\n"
        f"{'\n'.join(device_lines)}\n\n"
        "## Home Assistant Device information\n\n"
        f"{home_assistant}\n"
        "## Checklist\n\n"
        "- [x] I have created a single PR per device.\n"
        "- [x] For lights, only generated gzipped lookup tables are included.\n"
        "- [x] I reviewed the generated files and JSON in Powercalc Measure.\n\n"
        "## Additional info\n\n"
        f"{additional_info}\n\n"
        "### Generated files\n\n"
        f"{files}\n\n"
        "### Duplicate warnings\n\n"
        f"{warning_lines}\n"
    )


def _branch_part(value: str) -> str:
    normalized = "".join(character if character.isalnum() else "-" for character in value.lower())
    return "-".join(part for part in normalized.split("-") if part)
